name: Verify Terraform
description: Initialise and verify the Terraform configuration

runs:
  using: composite
  steps:
  - name: Detect Terraform version
    id: terraform_version
    shell: bash
    run: echo "version=$(cat .terraform-version)" >> "$GITHUB_OUTPUT"
  - name: Set up Terraform
    uses: hashicorp/setup-terraform@dfe3c3f87815947d99a8997f908cb6525fc44e9e # v4.0.1
    with:
      terraform_version: ${{ steps.terraform_version.outputs.version }}
  - name: Initialise with no backend
    shell: bash
    run: terraform init -backend=false
  - name: Check formatting
    shell: bash
    run: terraform fmt -check -recursive
  - name: Validate configuration
    shell: bash
    run: terraform validate
